### ISSUE TITLE
Creation of an Alternate Cycle process does not work

### ISSUE THREAD

**Issue by eschell** [CARLI/select#11]
Creation of an Alternate Cycle process does not work. ~~We also need to be able to delete cycles if needed.~~ 

Delete cycle moved to #34.

**Comment by mekane** [comment]
I was able to recover the code that Patrick and I came up with to make this work, and added it to the repository on the current development branch. I confirmed that it works on my local instance.

**Comment by kllittle** [comment]
Hello,
I went onto test   https://select-staff-test.carli.illinois.edu/subscription/7fcfb8f7-1647-4cd6-a68c-9045e0bffa1b    to create an alternate cycle and it is still stopping at 1% .

**Comment by mekane** [comment]
Sorry @kllittle the code hasn't been pushed to test yet

**Comment by mekane** [comment]
We have tested this locally and on the develop server. It seems to work fine, but I got a red error during one of my test cycles and this ended up creating the database but not the actual cycle. Let us know if you run into that.

**Comment by mekane** [comment]
Done and on production
