### ISSUE TITLE
New behavior for prices that have not been updated

### ISSUE THREAD

**Issue by eschell** [CARLI/select#13]
The system is designed to display last year’s pricing as a base for vendors.  But we have discovered that if a vendor does not change a price (as in they offered it to a school last year but not this year) the system will just show the 2016 price as the 2017 price.  

NOTE:
The system should display ONLY pricing that has been updated (has a white cell).

**Comment by mekane** [comment]
Update after working session at CARLI office this morning:
We decided that the easiest solution will be to 

1) add the same color hinting to the staff app as exists in the vendor app (e.g. white cells for updated prices, purple for those that have not been updated)

2) Add logic in the Library app to make sure that offerings without updated pricing are considered to be "display without pricing", and that they are omitted from "select last year".

**Comment by mekane** [comment]
Another task, uncovered while we did part 1:

3) Make sure that when the site license price is edited in the staff app, this does update the vendorModifiedSitePrice property, so that the library app will correctly display the price.

**Comment by mekane** [comment]
Done and on production
