### ISSUE TITLE
Making sent invoices static

### ISSUE THREAD

**Issue by eschell** [CARLI/select#18]
Making invoices static documents (PDF2) that will not be altered by subsequent changes (which should initiate a new document)

NOTE:
Library invoices will go out in early July and this needs to be addressed as soon as possible after the system is closed to the libraries.

**Comment by patrickzurek** [comment]
We believe the particular issue with the invoices not showing the correct date they were generated on should be fixed.  See two screenshots below from devel server.  The first showing a line in the sent notification history and then after clicking PDF, showing the output with the date 1/4/17 in the top right.

------------------
Sent history 
------------------
<img width="840" alt="notification" src="https://user-images.githubusercontent.com/6615138/28028078-f8dd3afe-6560-11e7-91da-e884fc9f5be8.png">


------------------
PDF
------------------


<img width="840" alt="invoicedate" src="https://user-images.githubusercontent.com/6615138/28028087-03d425b2-6561-11e7-9b0a-a7faf0210b09.png">

**Comment by patrickzurek** [comment]
This is deployed on test and is ready to be looked at.

**Comment by patrickzurek** [comment]
For test, please see my comment attached to #16 about logging in and your password.

**Comment by eschell** [comment]
From Katrina Little:
"I went in through the staff app and changed the price of something.  The price change was automatically reflected in the invoice dated 1/04/17.  The price on the databases are still dynamic."

The date is static, so that part is fixed.

**Comment by patrickzurek** [comment]
A fix has been made to keep the invoices static after an offering's price has changed.  It's on select-test.  @kllittle please take a look.

**Comment by kllittle** [comment]
I changed the price in the staff app and the price and date stayed the same in the staff and library app.  I am happy with this fix.

Thanks!!

**Comment by patrickzurek** [comment]
Great.  Just let me know when you'd like me to move it to production.

**Comment by kllittle** [comment]
You can move this to production whenever you are ready.

Thanks!!

**Comment by patrickzurek** [comment]
I'll move it in a half hour (so about 11:45am) and then send a note.  The Select process will be restarted as well.

**Comment by patrickzurek** [comment]
fc8613620249baf40660d80b478927e9a763e907 is on prod now.
