### ISSUE TITLE
correct JSON subscription output

### ISSUE THREAD

**Issue by eschell** [CARLI/select#19]
The JSON output from any cycle is not complete and will vary randomly

**Comment by eschell** [comment]
Starting point is /middleware/components/public.js
The function is listSelectedProductsFromActiveCyclesForLibrary

From there traced it to /CARLI/Entity/OfferingRepository.js and the function is called listSelectedProductsFromActiveCyclesForLibrary

**Comment by patrickzurek** [comment]
Fixed (880178d) the bug where more than one offering with the same ID from different active cycles was showing up in the feed:

        {
            "productName": "Communication and Mass Media",
            "vendorName": "xxx",
            "cycleName": "Fiscal Year 2015",
            "cycleYear": 2015
        },
        {
            "productName": "Communication and Mass Media",
            "vendorName": "xxx",
            "cycleName": "Fiscal Year 2017",
            "cycleYear": 2017
        },

The api feed will now only show offerings with the same ID once, reducing the above to one or the other but not both.  It will return the first offering retrieved from any active cycle (active being defined as not-archived) so the results are not guaranteed to be entirely deterministic as it is currently designed.

**Comment by patrickzurek** [comment]
Accidentally closed the issue.  The fix is on test.  Let me know when I can move it to production.

**Comment by eschell** [comment]
This is ready for production.
thanks

**Comment by patrickzurek** [comment]
It's on prod.
