### ISSUE TITLE
Membership Invoices excel shows 'undefined'

### ISSUE THREAD

**Issue by eschell** [CARLI/select#20]
When generating the membership invoices the excel report only has an error of 'undefined'.
[FY18 Membership Banner Feed.xlsx](https://github.com/CARLI/select/files/1129013/FY18.Membership.Banner.Feed.xlsx)

**Comment by eschell** [comment]
What is the work flow to duplicate this issues? What page/URL is this report generated from?

**Comment by eschell** [comment]
https://select-staff.carli.illinois.edu/membership/2018

From the Membership tab, hit the Invoice FY2018 button at the bottom.  Anytime you hit an invoice button, you get a Notification pop up.  When the notifications are created the banner feed is generated.  Attached is a spreadsheet showing exactly what it should have looked like minus the ARTERM.

**Comment by bgant** [comment]
At Patrick's request, I ran the following command on the Test and Dev servers to block any outgoing e-mail generated by the application:

sudo ufw deny out 25

**Comment by eschell** [comment]
From Katrina Little:
"I could be wrong, but here are my thoughts on the Membership/IShare invoicing.  There is no place for us to enter the detail code for either of these.  When we enter new databases, there is a place to enter the detail code.   I don’t know if there is a way to tell the system that the dollar amounts under the membership column should be USIA and the IShare amounts should be USIF, but I think that is why it does not like to create a Banner feed for the membership/IShare invoices. "

**Comment by patrickzurek** [comment]
There was a bug in the code that was found and fixed.  The change is on test.  Please take a look.

**Comment by patrickzurek** [comment]
Katrina, your comment on 7/26 is appreciated.  Any extra information is always useful!  However you might find this remark from Marty useful.  I paraphrase: "...by design the system will associate USIA with membership and USIF with IShare amounts.  It's hard-coded into the system."

**Comment by patrickzurek** [comment]
One last thing, you may need to do a hard refresh in your browser to get the change to show up on your side.

**Comment by patrickzurek** [comment]
The change has been moved from test to production.
