### ISSUE TITLE
No vendor list or access to new Calendar Year cycle

### ISSUE THREAD

**Issue by eschell** [CARLI/select#23]
When creating a new Calendar Year, 2018, the list of vendors does not show up.

1. From the staff app got to 'Subscriptions'
2. Create a New Cycle, base the cycle on the past one, 2017.
3. After the cycle is created, takes a few minutes, there should be a list of vendors that need to added/edit prices. That list will be the same as 2017 since we based 2018 on it. 

You can take a look at Calendar Year 2017 from the Subscriptions list to get an idea of the vendors that should show up.

If you masquerade as one of those vendors you get the message 'There are currently no products that require pricing. Please contact CARLI if you have any questions.'

**Comment by patrickzurek** [comment]
My initial thought is Select is choking on the same bad data in the database that it was encountering in issue #16.

**Comment by patrickzurek** [comment]
Suspicion was correct.  The same data that prevented the list of vendors from displaying in #16 is causing it to fail here.  I have added similar guards/checks in the two locations I found that were preventing the newly created CY from display vendors.  I will leave this ticket open while I look for other places checks might be needed.  

As mentioned in #16, we should consider purging the database of the faulty data as well.

Should I move this change to the test server and refresh the couch db?

**Comment by bgant** [comment]
Yes. If you have a fix on Dev, go ahead and move to Test.

**Comment by patrickzurek** [comment]
This has been moved to Test and pushed to the local git server.  I rebuilt the browserClient with `grunt build` and restarted carlictl.  Don't forget to do a hard refresh in your web browser if you're not picking up the changes.

**Comment by eschell** [comment]
The fix from Issue #16 did fixed the vendor list showing up. 

But the ability for the vendors to edit/add/etc pricing is still there. 

If you masquerade as a vendor from the list for that cycle you get the message, 'There are currently no products that require pricing. Please contact CARLI if you have any questions.'
When the vendor should see the ability to edit the products they offered last time and add new ones.

**Comment by patrickzurek** [comment]
This stems from a typo during the setup and configuration of the new production server.  A cron job designed to sync the couch databases and scheduled to run nightly around 2 am during low usage had a typo in it made by me.  I've manually fixed the typo.  This issue should be working tomorrow after the sync runs early tomorrow morning.

**Comment by patrickzurek** [comment]
This change has been moved from test to production.  A separate issue will be created for the problem described in the previous comment (https://github.com/CARLI/select/issues/23#issuecomment-324724604).
