### ISSUE TITLE
Email not being sent

### ISSUE THREAD

**Issue by eschell** [CARLI/select#24]
Email is not being sent from any of the apps; staff, vendor, library. This is affecting the ability for the staff app to send out invoices and for the vendor and library app to send password resets when necessary.

**Comment by patrickzurek** [comment]
Katrina:
Please try out emails on test and see if they're working now. 

I've configured test like this:

```
    "overrideTo": "kllittle@uillinois.edu",
    "carliListServe": "eresource_internal@carli.illinois.edu",
    "carliSupport": "support@carli.illinois.edu"
```

and prod is like:

```
    "carliListServe": "eresource_internal@carli.illinois.edu",
    "carliSupport": "support@carli.illinois.edu"
```


The purpose of the overrideTo field (and absence of it from prod) is to override the recipient of any emails from the system.  (I think password requests are included in this).  It's supposed to be used on test systems so you can test without any emails actually being sent to vendors or libraries.

**Comment by patrickzurek** [comment]
On select-prod emails are configured with these addresses:
```
"from": "kllittle@uillinois.edu"
"carliListServe": "eresource_internal@carli.illinois.edu"
"carliSupport": "support@carli.illinois.edu"
```

On the test server, like this:
```
"overrideTo": "kllittle@uillinois.edu"
"from": "kllittle@uillinois.edu"
"carliListServe": "eresource_internal@carli.illinois.edu"
"carliSupport": "support@carli.illinois.edu"
```

The _overrideTo_ setting is configured on the select-test server for the express purpose of test sending emails.  It will automatically override and replace the recipient of all emails sent from the app with the configured email address.
