### ISSUE TITLE
Add configurable SMTP server option for nodemailer transport

### ISSUE THREAD

**Issue by patrickzurek** [CARLI/select#25]
Currently, the nodemailer module uses direct-transport.

**Comment by patrickzurek** [comment]
This change is on test.  @kllittle Can you test send a couple emails from select-test -- they should be delivered to you like normal (per the configured override field)?  Assuming it works, can I go ahead and push to prod when I get a chance?

**Comment by patrickzurek** [comment]
Select on test is available again.  It was offline since Friday because I failed to change the local.json config file that the new code change called upon.  @kllittle Please give this a test and if it looks ok we can push to prod.

**Comment by kllittle** [comment]
I have tested the email in the staff and library apps and did not find any problems.

Thanks,
Katrina

**Comment by patrickzurek** [comment]
@kllittle:  Since the overrideTo field is not configured on production (because it makes no sense there), do you have any way of testing this change is working correctly when it's applied to prod?  Are you able to get select-prod to send a test email, one that won't get sent to vendors or libraries?

Essentially what I'm asking is, after the change is moved to prod, we'll have some way of testing if it's not working other than hearing from libraries & vendors that they aren't getting emails.

**Comment by patrickzurek** [comment]
@kllittle Disregard my last comment/question.

**Comment by kllittle** [comment]
HI Patrick,
We have a vendor trying to set a password and they are not getting the email to set it.  I know this feature is working in test.

**Comment by patrickzurek** [comment]
Katrina,

I don't see your message at the bottom in the thread for issue #25 (https://github.com/CARLI/select/issues/25).  Did you delete it from the thread?  Trying to figure out how this happened.  So is this still an issue?


Just to be clear, #25 has not been pushed to prod yet.  No change has been made there.  

I just tested sending out a couple reset emails from prod, both to an address of mine on-campus and an address off-campus.  Both were delivered.

It's possible that the vendors reset email isn't being delivered because the mail delivery subsystem on Select-prod is still using direct-transport for delivery.  If this is why, then I can go ahead and move the change in #25 to production and see if that clears it up.

Alternatively, if you provide me with the email of the vendor I can check the logs and observe the network traffic being sent when I trigger a reset to that address.  This will help troubleshoot whether it's not being delivered because it's blocked in transit or not accepted at this local mailserver because direct-transport is still in use on prod.

Let me know how you'd like to go forward.

Pat


________________________________________

**Comment by kllittle** [comment]
I did delete the comment.  I think it might have been a user error on our end.  I used my gmail account to create a vendor user and I received the email to reset password.  We have not heard anything back from the vendors that were having the problem yesterday morning before I made changes to the email addresses that were put in the system.  I apologize for any confusion this might have caused you.

**Comment by patrickzurek** [comment]
It's no problem.  I was unsure how Github handled comment edits and deletions when I first started using it too.  

If you post a new comment it automatically gets sent to all participants, listeners and people you've tagged with @.  However, if you later edit or delete the comment, subsequent notifications of the edit or removal are not sent.


For comments that have had an edit (unless something sensitive was inadvertently posted - then delete will be warranted), let's make judicious use of strikethrough* and add the new edit to the appropriate place in that comment.  This'll help avoid confusion when someone reads a comment in their inbox but sees something a little different on the site.

If I comment will be deleted lets try to post a follow-up comment with the reason why such as "Previous comment deleted -- issue was resolved."  


*To use strikethrough while posting a comment use double tildes before and after the part to mark.   Like  ~~this section of text is no longer valid~~.   The ~~ is part of Markdown syntax which is what github defaults to for formatting text.

Pat

**Comment by patrickzurek** [comment]
Just a follow-up.  Email responses do not support Markdown syntax.  If you look at the previous comment of mine, you'll see the ~~ where interpreted literally.

You have to make or edit the comment on Github.com in the text area they provide in order for Markdown syntax to properly be interpreted.

This should ~~not~~ work because I'm typing my comment on the website.

**Comment by mekane** [comment]
This went with the last push to production
