### ISSUE TITLE
Problem with api list-subscriptions-for-library

### ISSUE THREAD

**Issue by patrickzurek** [CARLI/select#26]
Two product offerings are showing up in the public api: api/public/list-subscriptions-for-library/9

```
{
            "productName": "Communication and Mass Media Complete",
            "vendorName": "EBSCO",
            "cycleName": "Fiscal Year 2015",
            "cycleYear": 2015
        },
        {
            "productName": "Communication and Mass Media Complete",
            "vendorName": "EBSCO",
            "cycleName": "Fiscal Year 2016",
            "cycleYear": 2016
        },
```

Even though it should only choose one (arbitrarily).  

Speculated to be either duplicate offerings or a problem in the logic or two products same name, different IDs.

**Comment by eschell** [comment]
each one is coming from a different "cycleName". The real problem is that there may also be 

{
            "productName": "Communication and Mass Media Complete",
            "vendorName": "EBSCO",
            "cycleName": "Fiscal Year 2018",
            "cycleYear": 2018
        },

that should show up but it's not.

**Comment by patrickzurek** [comment]
Hold off on looking at this for a little bit I'll start writing up your bit first with what we found.

Sent from my iPad

On Sep 14, 2017, at 8:55 AM, Ed <notifications@github.com<mailto:notifications@github.com>> wrote:


each one is coming from a different "cycleName". The real problem is that there may also be

{
"productName": "Communication and Mass Media Complete",
"vendorName": "EBSCO",
"cycleName": "Fiscal Year 2018",
"cycleYear": 2018
},

that should show up but it's not.

**Comment by patrickzurek** [comment]
Related to #19
