### ISSUE TITLE
Investigate the lack of option to archive a cycle

### ISSUE THREAD

**Issue by patrickzurek** [CARLI/select#27]
https://select-devel.carli.illinois.edu/subscription/6de511e4-7f3b-4b10-b3ec-28a4af7a7ff3

Ex: Fiscal Year 2015 is showing up in subscriptions list because it is still considered 'active' by the system.   In other words, it has not been archived yet.   From the staff user's point of view, some cycles are no longer considered active though.  There should be an option/button to switch a cycle to 'archived' at the url above.

**Comment by mekane** [comment]
Obsoleted by #45
