### ISSUE TITLE
Switch 'Report a Bug' to use Github issue tracker instead of JIRA

### ISSUE THREAD

**Issue by patrickzurek** [CARLI/select#30]
All Select pages contain clickable text in the bottom left labelled "Report a Bug" that pops a modal dialogue letting the user (staff, vendor, library) submit details related to an issue.  This gets logged to a remote JIRA instance using the JIRA Issue Collector Plugin.

Change this so that it creates an issue in our Github issue queue with the same information.

**Comment by patrickzurek** [comment]
<img width="805" alt="screen shot 2017-10-18 at 11 00 54 am" src="https://user-images.githubusercontent.com/6615138/31729391-7c998442-b3f4-11e7-836b-d7c23a41ffd0.png">

**Comment by patrickzurek** [comment]
Switching the "Report a Bug" button to use Github's issue queue isn't straight-forward.  Can it be removed entirely?

**Comment by eschell** [comment]
Maybe we can have an email link to support@carli.illinois.edu

**Comment by patrickzurek** [comment]
The Ask CARLI <img width="127" alt="screen shot 2017-11-01 at 2 08 20 pm" src="https://user-images.githubusercontent.com/6615138/32292423-28f9b210-bf0e-11e7-905f-1bae029a41ba.png"> button will still be there.  It's just to the upper left of the bug button on most pages.

It goes to either support or the eresource listserv.  I can't remember which.

**Comment by patrickzurek** [comment]
We should remove it or change what it does so PIXO can shut down their JIRA instance.

**Comment by patrickzurek** [comment]
Need to add "Ask CARLI" button to all pages that don't have it.

**Comment by mekane** [comment]
The pixo jira plugin is removed from the live sites as of the last push to production
