### ISSUE TITLE
Select Last Year's Subscription selecting "Do Not Display" subscriptions

### ISSUE THREAD

**Issue by patrickzurek** [CARLI/select#32]
Split off from #17, @kllittle said:

If a library selected a product last year that we do not know we will be able to offer this year due to contract negotiations, a product might be marked as Do Not Display. If the library hit Select Last Year's Subscription it will select the product that is marked Do Not Display at last years price if no new pricing has been entered. It shows up in the reports for Selected Products and Selections by Vendor. We will do some further testing and expand on these tomorrow. I apologize for the delay in my response.

**Comment by patrickzurek** [comment]
We replicated this.  A product marked _Do Not Display_ is still added to selections and shown when reviewed on the next page.  Additionally, on the page where the product isn't shown, its price was included in the total at the bottom.

**Comment by patrickzurek** [comment]
/libraryApp/components/subscriptionSelections/subscriptionSelections.controller.js, line 67, may need to be changed to filter out "Do Not Display" products.

**Comment by mekane** [comment]
We re-worked the controller for the display screen to have better, more fine-grained logic for deciding then to show products vs. not.

**Comment by mekane** [comment]
Done and on production
