### ISSUE TITLE
Add ability to delete cycles when necessary

### ISSUE THREAD

**Issue by patrickzurek** [CARLI/select#34]
<nt>

**Comment by mekane** [comment]
Our plan is to add a tiny admin screen called "Delete Cycles" under the gear menu. It will list all the active cycles and include a delete button. 

We also plan to add a preview of the actual cycle name in the create cycle dialog, which will hopefully help prevent ever creating a cycle with an unexpected name. This is an almost-trivial amount of effort to add.

**Comment by mekane** [comment]
Done and on production
