### ISSUE TITLE
Vendor app: no export unless save

### ISSUE THREAD

**Issue by eschell** [CARLI/select#35]
While vendors are putting in prices and increases they are able to export to a file. At the moment it will export any changes they have made but not saved. If they have made changes, export those changes to a file, but _forget to save the changes_ to the selection system their pricing list will be different from our pricing list.

We would like to make the export function dependent upon saving any changes first

**Comment by patrickzurek** [comment]
To clarify, this is asking for the export option to only be available/succeed when there’s no unsaved changes pending in the vendor’s pricing list?



On Dec 6, 2017, at 9:50 AM, Ed <notifications@github.com<mailto:notifications@github.com>> wrote:


While vendors are putting in prices and increases they are able to export to a file. At the moment it will export any changes they have made but not saved. If they have made changes, export those changes to a file, but forget to save the changes to the selection system their pricing list will be different from our pricing list.

We would like to make the export function dependent upon saving any changes first

**Comment by eschell** [comment]
That is correct. 
We have had an instance where a vendor put in their pricing, exported the pricing, but did not save and then logged out. Thinking they had updated the prices. The pricing that the institutions then saw was from last year but wrong. The vendor had the export with the correct pricing to show that they had updated the prices.

**Comment by mekane** [comment]
We used the existing change detection on the site license screen to disable the save button until there are changes, and disable the csv export button while there are changes.

**Comment by mekane** [comment]
Done and on production
