### ISSUE TITLE
Fix display issues for read only library users

### ISSUE THREAD

**Issue by eschell** [CARLI/select#4]
Library users that have read only access cannot see the current offerings (when the system is open to libraries) and get a ‘forbidden’ message when they try.  We would like for them to be able to get into the current selections being offered and see everything but the radio button for making a selection.  The original intent of this feature was to let other librarians in to help with decisions about products to add or drop, but they cannot do that if they aren’t able to see the current offering information.

**Comment by mekane** [comment]
Update after working session at CARLI office this morning: we couldn't find a specific user that reproduced this, but I think it must be something specific to how the user's permissions are set up in couch. We will try and reproduce with different combinations of library users and see if we can figure out why it's happening. 

If necessary we will remove the database permission part and simply not show any editable controls in the app for this type of user.

**Comment by mekane** [comment]
We reproduced the "forbidden" message and have fixed that.

We want to confirm that read-only users should be able to see prices but not make selections. Is that right? (Currently the buttons that would let them make selections are hidden, but they contain the prices so read-only users can't see any prices)

**Comment by mekane** [comment]
We went ahead and added special price displays for the read-only users so that can see all of the information but not modify it.

**Comment by mekane** [comment]
Katrina reported that read-only users can still see the "remove" button on selections. I will remove that ability.

**Comment by mekane** [comment]
Done and on production
