### ISSUE TITLE
Track "select last year" and vendor activity in revision history

### ISSUE THREAD

**Issue by eschell** [CARLI/select#5]
1. On the Dashboard under ‘Subscription: Recent Activity’ we see many instances of a library selecting the same product multiple times.
2. On Revision History – the system does not currently track when a library selects ‘Renew Last Year’s Subscriptions’.  This is a vital piece of the historical record.
3. On Revision History – vendors should also be included here.  This would require an additional sort button for ‘Show Vendor Revisions’

**Comment by mekane** [comment]
Update after working session at CARLI office this morning:
1) We will double check what triggers these library events. Cindy will let us know what specific examples look like to see if there is any correlation.

2) We will add tracking for "review last year"

3) We will build out the vendor events for revision history

**Comment by mekane** [comment]
1. Confirmed that any click of a selection button in the library app immediately updates the selection and also logs an event.

2. Added this

3. BDub will work on this next:

a) Add vendor filter to revision history screen
b) log product description changes (log each product individually)
c) log SU price changes (log each product individually)
d) log Site License price changes (log each product + library individually)

**Comment by mekane** [comment]
Done and on production
