### ISSUE TITLE
Notifications - open system estimates not attaching to emails

### ISSUE THREAD

**Issue by kllittle** [CARLI/select#56]
When sending the notifications, the attachments are not going.  I have sent 104 Estimates to the libraries and not one of them contained the attachment.  It looks like it might just be a problem with the Open System Estimate.  I resent an invoice and the attachment sent.

**Comment by kllittle** [comment]
Closed system estimates are also not attaching.

**Comment by mekane** [comment]
From Katrina via email: 

> The database estimates have all been sent out with the attached PDF successfully.
