### ISSUE TITLE
Library Reporting Issue with Password Reset

### ISSUE THREAD

**Issue by CClennon** [CARLI/select#90]
I just spoke with Russ Kracke at Oakton Community College.  He needed to reset his password and after requesting and receiving the reset message, when he clicks on the link in the reset email he gets a blank screen.  This is the first we have heard of this being a problem but it does not sound like user error.

Thanks!

**Comment by bdcribbs** [comment]
I have not had any luck reproducing this behavior, but my first recommendation would be to try opening the link in a different web browser.  If that fixes the problem it would be useful to know which OS and browser he is using.

**Comment by CClennon** [comment]
Russ successfully made CY19 selections on 10/22 so this issue can be closed.
