### ISSUE TITLE
Masquerading Still not Working in Select-staff-stage

### ISSUE THREAD

**Issue by CClennon** [CARLI/select#91]
Hi all,

Our testing has been impacted by still not being able to masquerade as libraries.  Here is what we see when we try:

![image](https://user-images.githubusercontent.com/33095526/49317098-c3be7980-f4b8-11e8-9f0d-6515bdcf8790.png)

When we try to masquerade as a vendor we just get a blank screen after selecting the vendor.

Our testing has been stalled by two major projects which have been blowing up for the last few weeks but until we are able to successfully masquerade we can't really get much done.

Thanks!

**Comment by bdcribbs** [comment]
I've deployed an update.  Note that when you might still see the broken page the first time you try.  If so manually refresh the page in your browser.  (That should only happen once, subsequent attempts should be back to normal behavior without a manual page reload).
